{% set name = "large-image" %}
{% set version = "1.27.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 72f80ba51f04446cb08278bd3c71e15f457c735a83bef7bc60251ca94066b33b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - python >=3.8
    - setuptools
    - cachetools >=3.0.0
    - Pillow
    - psutil >=4.2.0
    - numpy >=1.10.4
    - palettable

test:
  imports:
    - large_image

about:
  home: https://github.com/girder/large_image
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python modules to work with large, multiresolution images.
  description: |
    Python modules to work with large, multiresolution images. Large Image is developed and maintained by the Data & Analytics group at Kitware, Inc. for processing large geospatial and medical images.
  doc_url: https://girder.github.io/large_image/
  dev_url: https://github.com/girder/large_image

extra:
  recipe-maintainers:
    - banesullivan
    - manthey
    - giswqs
