{% set name = "large-image" %}
{% set version = "1.32.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 691b92c4544456bc5fef29d337e7a8b3979e25351c9828547a18ca202680f5e4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - setuptools
    - cachetools >=3.0.0
    - Pillow
    - psutil >=4.2.0
    - numpy >=1.10.4
    - palettable
    - typing_extensions

test:
  requires:
    - python {{ python_min }}
  imports:
    - large_image

about:
  home: https://github.com/girder/large_image
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python modules to work with large, multiresolution images.
  description: |
    Python modules to work with large, multiresolution images. Large Image is developed and maintained by the Data & Analytics group at Kitware, Inc. for processing large geospatial and medical images.
  doc_url: https://girder.github.io/large_image/
  dev_url: https://github.com/girder/large_image

extra:
  recipe-maintainers:
    - banesullivan
    - manthey
    - giswqs
