{% set name = "large-image" %}
{% set version = "1.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8b4bc8515ac27b3813dd241473f3a7129f9907631a8c1c43705cf8b41f345874

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - setuptools
    - cachetools >=3.0.0
    - Pillow
    - psutil >=4.2.0
    - numpy >=1.10.4
    - palettable
    - importlib-metadata

test:
  imports:
    - large_image

about:
  home: https://github.com/girder/large_image
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python modules to work with large, multiresolution images.
  description: |
    Python modules to work with large, multiresolution images. Large Image is developed and maintained by the Data & Analytics group at Kitware, Inc. for processing large geospatial and medical images.
  doc_url: https://girder.github.io/large_image/
  dev_url: https://github.com/girder/large_image

extra:
  recipe-maintainers:
    - banesullivan
    - manthey
    - giswqs
